# Generated by Django 2.2.3 on 2019-08-04 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='User',
            new_name='user',
        ),
    ]
